---
title: "Reproducible Research: Peer Assessment 1"
author: "Majid"
date: "March 17, 2016"
output: 
  html_document: 
    self_contained: no
---


## Loading and preprocessing the data
```{r}
# load packages
suppressPackageStartupMessages({
  library(magrittr)
  library(dplyr)
  library(ggplot2)
})

# import data
data <- read.csv("activity.csv",stringsAsFactors = F)

# save date as POSIXct
data$date <- as.POSIXct(data$date, format = "%Y-%m-%d")

head(data)

```



## What is mean total number of steps taken per day?
```{r}
# plot total
ggplot(aes(date, steps), data = na.omit(data)) +
geom_bar(stat = "identity", fill = "lightblue") + 
labs(title = "Total number of steps per day") + 
ylab("Steps") + 
xlab("Date") 

# summarise means
data %>% 
  na.omit() %>% 
  group_by(date) %>% 
  summarize(
    mean = mean(steps, na.rm = TRUE), 
    median = median(steps, na.rm = TRUE)
  )
```

## What is the average daily activity pattern?
```{r}
# summarise mean per interval
data %>% 
na.omit() %>% 
  group_by(interval) %>% 
  summarise(mean(steps)) %>% 
  set_names(c("interval", "mean")) ->
avgPatternData

# means per interval
head(avgPatternData)

# total mean
mean(data$steps, na.rm = TRUE)

# total media
median(data$steps, na.rm = TRUE)

# plot means
avgPatternData %>% 
ggplot(., aes(interval, mean)) + 
  geom_line(color = "steelblue", size = 0.8) + 
  labs(title = "Mean of steps per interval") + 
  ylab("Mean of steps") + 
  xlab("Interval of 5 minutes") 

# extract highest mean
avgPatternData %>% 
  extract(
    .$mean %>% 
      equals(max(avgPatternData$mean)) %>% 
      which(),
  )
```

## Imputing missing values

```{r}
# count NAs
data %>% 
  apply(1, function(row) any(is.na(row))) %>% 
  as.numeric() %>% 
  sum()

# replace NAs with mean 
data %>% 
  apply(1, function(row, avgPatternData) {
    
    if (is.na(row["steps"])) {
      
      row %<>%
        inset(
          "steps",
          avgPatternData %>% 
            filter(interval == as.numeric(row["interval"])) %>% 
            extract2("mean") 
        )

    }
     row
  },
  avgPatternData = avgPatternData) %>% 
  t() %>% 
  as.data.frame(stringsAsFactors = FALSE) %>% 
  mutate(
    steps = as.numeric(steps),
    interval = as.numeric(interval)
  ) ->
replacedNAData

# save date as date again
replacedNAData$date <- as.POSIXct(replacedNAData$date, form = "%Y-%m-%d")

# plot replaced NA data
replacedNAData %>% 
  group_by(date) %>% 
  summarise(mean(steps)) %>%
  set_names(c("date", "mean")) %>% 
  ggplot(data = ., aes(date, mean)) +
  geom_bar(stat = "identity", fill = "lightblue") + 
  labs(title = "Means of of steps with replaced NAs") + 
  ylab("Mean of steps") + 
  xlab("Date")

# compare new and old median
median(replacedNAData$steps)  - median(data$steps, na.rm = TRUE)

# compare new and old mean
mean(replacedNAData$steps)  - mean(data$steps, na.rm = TRUE)

```


## Are there differences in activity patterns between weekdays and weekends?

```{r}
# add weekend variable to replacedNAData
replacedNAData %<>% 
  mutate(
    weekend = date %>% 
                weekdays() %in% (c(
                  "Samstag",
                  "Sonntag"
                )) %>%
      as.numeric()
  )

# transform weekend variable to a factor
replacedNAData$weekend <- factor(replacedNAData$weekend, levels = c(0,1), labels = c("weekday", "weekend"))

# plot comparison of weekday and weekend
replacedNAData %>% 
  group_by(weekend, interval) %>% 
  summarize(mean(steps, na.rm = TRUE)) %>% 
  set_names(c("weekend", "interval", "mean")) %>% 
  ggplot(., aes(interval, mean)) + 
  geom_line(color = "steelblue", size = 0.8) +
  facet_grid(. ~ weekend) +
  labs(title = "Comparison of activity patterny by weekday & weekends") + 
  ylab("Mean of steps") + 
  xlab("Interval of 5 minutes")

```







